const Book = require('../models/Book');
const Category = require('../models/Category');

const seedBooks = async () => {
  const count = await Book.countDocuments();
  if (count > 0) {
    console.log('Books already seeded');
    return;
  }

  // Fetch all categories to get their IDs
  const categories = await Category.find();
  const catMap = {};
  categories.forEach(cat => {
    catMap[cat.name] = cat._id;
  });

  const books = [
    // ═══════════════════════════════════════
    //  FICTION
    // ═══════════════════════════════════════
    {
      title: 'To Kill a Mockingbird',
      author: 'Harper Lee',
      isbn: '978-0-06-112008-4',
      description: 'A gripping, heart-wrenching, and wholly remarkable tale of coming-of-age in a South poisoned by virulent prejudice. Through the young eyes of Scout and Jem Finch, Harper Lee explores with exuberant humour the irrationality of adult attitudes to race and class in the Deep South of the 1930s.',
      publisher: 'HarperCollins',
      publishedDate: new Date('1960-07-11'),
      pageCount: 281,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1553383690i/2657.jpg',
      category: catMap['Fiction'],
      genres: ['Classic', 'Literary Fiction'],
      language: 'English',
      totalCopies: 5,
      availableCopies: 3,
      location: { shelf: 'A1', row: '1', section: 'Fiction' },
      averageRating: 4.8,
      numReviews: 12,
    },
    {
      title: '1984',
      author: 'George Orwell',
      isbn: '978-0-451-52493-5',
      description: 'Among the seminal texts of the 20th century, the novel is set in an imaginary future world dominated by three perpetually warring totalitarian police states. Winston Smith, employed as a records editor, secretly rebels against the party.',
      publisher: 'Signet Classics',
      publishedDate: new Date('1949-06-08'),
      pageCount: 328,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1657781257i/61439040.jpg',
      category: catMap['Fiction'],
      genres: ['Dystopian', 'Political Fiction'],
      language: 'English',
      totalCopies: 6,
      availableCopies: 4,
      location: { shelf: 'A1', row: '2', section: 'Fiction' },
      averageRating: 4.7,
      numReviews: 18,
    },
    {
      title: 'The Great Gatsby',
      author: 'F. Scott Fitzgerald',
      isbn: '978-0-7432-7356-5',
      description: 'The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, set against the backdrop of the Roaring Twenties. A masterful critique of the American Dream.',
      publisher: 'Scribner',
      publishedDate: new Date('1925-04-10'),
      pageCount: 180,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1490096506i/4671.jpg',
      category: catMap['Fiction'],
      genres: ['Classic', 'Literary Fiction'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 2,
      location: { shelf: 'A1', row: '3', section: 'Fiction' },
      averageRating: 4.5,
      numReviews: 9,
    },
    {
      title: 'Pride and Prejudice',
      author: 'Jane Austen',
      isbn: '978-0-14-143951-8',
      description: 'Since its immediate success in 1813, this novel has remained one of the most popular novels in the English language. It portrays life in the genteel rural society of the day and tells of the initial misunderstandings and eventual romance between Elizabeth Bennet and Mr. Darcy.',
      publisher: 'Penguin Classics',
      publishedDate: new Date('1813-01-28'),
      pageCount: 279,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320399351i/1885.jpg',
      category: catMap['Fiction'],
      genres: ['Classic', 'Romance'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 3,
      location: { shelf: 'A1', row: '4', section: 'Fiction' },
      averageRating: 4.6,
      numReviews: 14,
    },
    {
      title: 'The Alchemist',
      author: 'Paulo Coelho',
      isbn: '978-0-06-112241-5',
      description: 'A mystical story about Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest leads him to riches far different from what he originally sought.',
      publisher: 'HarperOne',
      publishedDate: new Date('1988-01-01'),
      pageCount: 197,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1654371543i/18144590.jpg',
      category: catMap['Fiction'],
      genres: ['Adventure', 'Philosophical Fiction'],
      language: 'English',
      totalCopies: 5,
      availableCopies: 5,
      location: { shelf: 'A1', row: '5', section: 'Fiction' },
      averageRating: 4.4,
      numReviews: 22,
    },

    // ═══════════════════════════════════════
    //  SCIENCE
    // ═══════════════════════════════════════
    {
      title: 'A Brief History of Time',
      author: 'Stephen Hawking',
      isbn: '978-0-553-38016-3',
      description: 'A landmark volume in science writing by one of the great minds of our time. Hawking explores such profound questions as: How did the universe begin? Will it come to an end? What is the nature of time?',
      publisher: 'Bantam',
      publishedDate: new Date('1988-04-01'),
      pageCount: 256,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1333578703i/3869.jpg',
      category: catMap['Science'],
      genres: ['Physics', 'Cosmology'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 2,
      location: { shelf: 'B1', row: '1', section: 'Science' },
      averageRating: 4.6,
      numReviews: 15,
    },
    {
      title: 'The Selfish Gene',
      author: 'Richard Dawkins',
      isbn: '978-0-19-878860-7',
      description: 'Dawkins articulates a gene-centered view of evolution, arguing that the gene is the principal unit of selection in evolution. This brilliant reformulation of the theory of natural selection transformed the way we think about evolution.',
      publisher: 'Oxford University Press',
      publishedDate: new Date('1976-11-01'),
      pageCount: 360,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1528813612i/61535.jpg',
      category: catMap['Science'],
      genres: ['Biology', 'Evolution'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 1,
      location: { shelf: 'B1', row: '2', section: 'Science' },
      averageRating: 4.5,
      numReviews: 8,
    },
    {
      title: 'Cosmos',
      author: 'Carl Sagan',
      isbn: '978-0-345-53943-4',
      description: 'Cosmos retraces the fourteen billion years of cosmic evolution that have transformed matter into consciousness, exploring topics such as the origin of life, the human brain, Egyptian hieroglyphics, spacecraft missions, the death of the Sun, the evolution of galaxies, and the forces and individuals who helped to shape modern science.',
      publisher: 'Ballantine Books',
      publishedDate: new Date('1980-09-12'),
      pageCount: 396,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388213991i/55030.jpg',
      category: catMap['Science'],
      genres: ['Astronomy', 'Popular Science'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 4,
      location: { shelf: 'B1', row: '3', section: 'Science' },
      averageRating: 4.7,
      numReviews: 11,
    },
    {
      title: 'The Origin of Species',
      author: 'Charles Darwin',
      isbn: '978-0-451-52901-0',
      description: 'Darwin published his theory of evolution with compelling evidence in this groundbreaking work. It introduced the scientific theory that populations evolve over the course of generations through a process of natural selection.',
      publisher: 'Signet Classics',
      publishedDate: new Date('1859-11-24'),
      pageCount: 576,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1298425733i/22482.jpg',
      category: catMap['Science'],
      genres: ['Biology', 'Evolution', 'Classic'],
      language: 'English',
      totalCopies: 2,
      availableCopies: 2,
      location: { shelf: 'B1', row: '4', section: 'Science' },
      averageRating: 4.3,
      numReviews: 6,
    },
    {
      title: 'Astrophysics for People in a Hurry',
      author: 'Neil deGrasse Tyson',
      isbn: '978-0-393-60939-4',
      description: 'The essential, witty guide to understanding the universe from the author of Death by Black Hole. What is the nature of space and time? How do we fit within the universe? How does the universe fit within us?',
      publisher: 'W. W. Norton',
      publishedDate: new Date('2017-05-02'),
      pageCount: 224,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1488036501i/32191710.jpg',
      category: catMap['Science'],
      genres: ['Astrophysics', 'Popular Science'],
      language: 'English',
      totalCopies: 5,
      availableCopies: 3,
      location: { shelf: 'B1', row: '5', section: 'Science' },
      averageRating: 4.2,
      numReviews: 10,
    },

    // ═══════════════════════════════════════
    //  TECHNOLOGY
    // ═══════════════════════════════════════
    {
      title: 'Clean Code',
      author: 'Robert C. Martin',
      isbn: '978-0-13-235088-4',
      description: 'A handbook of agile software craftsmanship. Even bad code can function, but if code is not clean, it can bring a development organization to its knees. This book covers the principles, patterns, and practices of writing clean code.',
      publisher: 'Prentice Hall',
      publishedDate: new Date('2008-08-01'),
      pageCount: 464,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1436202607i/3735293.jpg',
      category: catMap['Technology'],
      genres: ['Programming', 'Software Engineering'],
      language: 'English',
      totalCopies: 6,
      availableCopies: 2,
      location: { shelf: 'C1', row: '1', section: 'Technology' },
      averageRating: 4.7,
      numReviews: 20,
    },
    {
      title: 'The Pragmatic Programmer',
      author: 'David Thomas & Andrew Hunt',
      isbn: '978-0-13-595705-9',
      description: 'Your journey to mastery. This classic teaches the philosophy of software development through practical tips and anecdotes. It covers topics from personal responsibility to architectural techniques.',
      publisher: 'Addison-Wesley',
      publishedDate: new Date('1999-10-20'),
      pageCount: 352,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1401432508i/4099.jpg',
      category: catMap['Technology'],
      genres: ['Programming', 'Software Engineering'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 3,
      location: { shelf: 'C1', row: '2', section: 'Technology' },
      averageRating: 4.6,
      numReviews: 13,
    },
    {
      title: 'Designing Data-Intensive Applications',
      author: 'Martin Kleppmann',
      isbn: '978-1-449-37332-0',
      description: 'Data is at the center of many challenges in system design today. Difficult issues need to be figured out, such as scalability, consistency, reliability, efficiency, and maintainability.',
      publisher: "O'Reilly Media",
      publishedDate: new Date('2017-04-18'),
      pageCount: 616,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1430614821i/23463279.jpg',
      category: catMap['Technology'],
      genres: ['Distributed Systems', 'Data Engineering'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 1,
      location: { shelf: 'C1', row: '3', section: 'Technology' },
      averageRating: 4.8,
      numReviews: 9,
    },
    {
      title: 'Eloquent JavaScript',
      author: 'Marijn Haverbeke',
      isbn: '978-1-59327-950-9',
      description: 'A modern introduction to programming. This book teaches the JavaScript language and programming in general. It covers the basics as well as advanced topics like asynchronous programming and the DOM.',
      publisher: 'No Starch Press',
      publishedDate: new Date('2018-12-04'),
      pageCount: 472,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1536143957i/39937662.jpg',
      category: catMap['Technology'],
      genres: ['JavaScript', 'Web Development'],
      language: 'English',
      totalCopies: 5,
      availableCopies: 4,
      location: { shelf: 'C1', row: '4', section: 'Technology' },
      averageRating: 4.5,
      numReviews: 11,
    },
    {
      title: 'Artificial Intelligence: A Modern Approach',
      author: 'Stuart Russell & Peter Norvig',
      isbn: '978-0-13-604259-4',
      description: 'The most widely used textbook in AI. It provides a comprehensive survey of AI techniques, covering search, logic, planning, probabilistic reasoning, machine learning, natural language processing, and robotics.',
      publisher: 'Pearson',
      publishedDate: new Date('2020-04-28'),
      pageCount: 1136,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1626752115i/27543.jpg',
      category: catMap['Technology'],
      genres: ['Artificial Intelligence', 'Machine Learning'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 2,
      location: { shelf: 'C1', row: '5', section: 'Technology' },
      averageRating: 4.4,
      numReviews: 7,
    },
    {
      title: 'You Don\'t Know JS Yet',
      author: 'Kyle Simpson',
      isbn: '978-1-091-21009-5',
      description: 'The bestselling JavaScript series, fully updated. Whether you\'re a new or experienced developer, this series takes you deep into JavaScript to give you the knowledge you need to truly understand the language.',
      publisher: 'GetiDB Publishing',
      publishedDate: new Date('2020-01-28'),
      pageCount: 278,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1588759221i/44137149.jpg',
      category: catMap['Technology'],
      genres: ['JavaScript', 'Web Development'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 4,
      location: { shelf: 'C1', row: '6', section: 'Technology' },
      averageRating: 4.6,
      numReviews: 8,
    },

    // ═══════════════════════════════════════
    //  HISTORY
    // ═══════════════════════════════════════
    {
      title: 'Sapiens: A Brief History of Humankind',
      author: 'Yuval Noah Harari',
      isbn: '978-0-06-231609-7',
      description: 'Explores how Homo sapiens came to dominate the Earth. It surveys the entire history of humankind, from the first humans in the Stone Age through the twenty-first century.',
      publisher: 'Harper',
      publishedDate: new Date('2014-01-01'),
      pageCount: 443,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1595674533i/23692271.jpg',
      category: catMap['History'],
      genres: ['Anthropology', 'World History'],
      language: 'English',
      totalCopies: 5,
      availableCopies: 3,
      location: { shelf: 'D1', row: '1', section: 'History' },
      averageRating: 4.6,
      numReviews: 19,
    },
    {
      title: 'Guns, Germs, and Steel',
      author: 'Jared Diamond',
      isbn: '978-0-393-31755-8',
      description: 'A short history of everybody for the last 13,000 years. Winner of the Pulitzer Prize, this groundbreaking work answers the question of why Eurasian peoples conquered or displaced Native Americans, Australians, and Africans.',
      publisher: 'W. W. Norton',
      publishedDate: new Date('1997-03-01'),
      pageCount: 480,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1453215833i/1842.jpg',
      category: catMap['History'],
      genres: ['Civilization', 'Sociology'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 2,
      location: { shelf: 'D1', row: '2', section: 'History' },
      averageRating: 4.4,
      numReviews: 10,
    },
    {
      title: 'The Art of War',
      author: 'Sun Tzu',
      isbn: '978-1-59030-225-3',
      description: 'The most influential treatise on war ever written. Dating from around 500 BC, Sun Tzu\'s classic work outlines principles of strategy that have been adopted throughout the world.',
      publisher: 'Shambhala',
      publishedDate: new Date('500-01-01'),
      pageCount: 67,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1630676054i/10534.jpg',
      category: catMap['History'],
      genres: ['Military Strategy', 'Philosophy'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 4,
      location: { shelf: 'D1', row: '3', section: 'History' },
      averageRating: 4.3,
      numReviews: 16,
    },
    {
      title: 'The Diary of a Young Girl',
      author: 'Anne Frank',
      isbn: '978-0-553-29698-3',
      description: 'The diary of Anne Frank is one of the most widely read books in the world. It tells the story of a young Jewish girl hiding from the Nazis during World War II, providing an extraordinary window into human courage.',
      publisher: 'Bantam',
      publishedDate: new Date('1947-06-25'),
      pageCount: 283,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1562696707i/48855.jpg',
      category: catMap['History'],
      genres: ['Memoir', 'World War II'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 3,
      location: { shelf: 'D1', row: '4', section: 'History' },
      averageRating: 4.6,
      numReviews: 13,
    },

    // ═══════════════════════════════════════
    //  PHILOSOPHY
    // ═══════════════════════════════════════
    {
      title: 'Meditations',
      author: 'Marcus Aurelius',
      isbn: '978-0-14-044933-4',
      description: 'Written in Greek by the only Roman emperor who was also a philosopher, without any intention of publication, the Meditations of Marcus Aurelius offer a remarkable series of challenging spiritual reflections and exercises.',
      publisher: 'Penguin Classics',
      publishedDate: new Date('180-01-01'),
      pageCount: 254,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1583139953i/30656611.jpg',
      category: catMap['Philosophy'],
      genres: ['Stoicism', 'Ancient Philosophy'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 3,
      location: { shelf: 'E1', row: '1', section: 'Philosophy' },
      averageRating: 4.7,
      numReviews: 14,
    },
    {
      title: 'Beyond Good and Evil',
      author: 'Friedrich Nietzsche',
      isbn: '978-0-14-044923-5',
      description: 'Nietzsche\'s most comprehensive and systematic work. He argues that the traditional notions of good and evil are not only false but harmful, and that humanity must move beyond them.',
      publisher: 'Penguin Classics',
      publishedDate: new Date('1886-01-01'),
      pageCount: 240,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388778612i/12319.jpg',
      category: catMap['Philosophy'],
      genres: ['Existentialism', 'Ethics'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 2,
      location: { shelf: 'E1', row: '2', section: 'Philosophy' },
      averageRating: 4.3,
      numReviews: 7,
    },
    {
      title: 'Sophie\'s World',
      author: 'Jostein Gaarder',
      isbn: '978-0-425-15225-5',
      description: 'A novel about the history of philosophy. Sophie Amundsen receives a mysterious letter that draws her into a fascinating journey through the entire history of Western philosophy.',
      publisher: 'Berkley Books',
      publishedDate: new Date('1991-01-01'),
      pageCount: 518,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1541422103i/10952.jpg',
      category: catMap['Philosophy'],
      genres: ['Philosophy', 'Fiction'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 3,
      location: { shelf: 'E1', row: '3', section: 'Philosophy' },
      averageRating: 4.2,
      numReviews: 6,
    },
    {
      title: 'The Republic',
      author: 'Plato',
      isbn: '978-0-14-045511-4',
      description: 'Plato\'s masterwork, one of the most influential works of philosophy and political theory ever written. It explores justice, the order and character of the just city-state and the just man.',
      publisher: 'Penguin Classics',
      publishedDate: new Date('-380-01-01'),
      pageCount: 416,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1386924120i/30289.jpg',
      category: catMap['Philosophy'],
      genres: ['Political Philosophy', 'Ancient Philosophy'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 3,
      location: { shelf: 'E1', row: '4', section: 'Philosophy' },
      averageRating: 4.1,
      numReviews: 5,
    },

    // ═══════════════════════════════════════
    //  BIOGRAPHY
    // ═══════════════════════════════════════
    {
      title: 'Steve Jobs',
      author: 'Walter Isaacson',
      isbn: '978-1-4516-4853-9',
      description: 'Based on more than forty interviews with Jobs conducted over two years, as well as interviews with more than a hundred family members, friends, adversaries, and competitors.',
      publisher: 'Simon & Schuster',
      publishedDate: new Date('2011-10-24'),
      pageCount: 656,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1511288482i/11084145.jpg',
      category: catMap['Biography'],
      genres: ['Technology', 'Business'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 2,
      location: { shelf: 'F1', row: '1', section: 'Biography' },
      averageRating: 4.5,
      numReviews: 16,
    },
    {
      title: 'Becoming',
      author: 'Michelle Obama',
      isbn: '978-1-5247-6313-8',
      description: 'An intimate, powerful, and inspiring memoir. Michelle Obama invites readers into her world, sharing the experiences that have shaped her, from her childhood on the South Side of Chicago to her years as an executive.',
      publisher: 'Crown',
      publishedDate: new Date('2018-11-13'),
      pageCount: 448,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1528809953i/38746485.jpg',
      category: catMap['Biography'],
      genres: ['Memoir', 'Politics'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 3,
      location: { shelf: 'F1', row: '2', section: 'Biography' },
      averageRating: 4.6,
      numReviews: 18,
    },
    {
      title: 'Einstein: His Life and Universe',
      author: 'Walter Isaacson',
      isbn: '978-0-7432-6473-0',
      description: 'The definitive biography of Albert Einstein, covering his scientific achievements, personal life, and the political and cultural contexts in which he lived and worked.',
      publisher: 'Simon & Schuster',
      publishedDate: new Date('2007-04-10'),
      pageCount: 704,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348349644i/977953.jpg',
      category: catMap['Biography'],
      genres: ['Science', 'Physics'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 2,
      location: { shelf: 'F1', row: '3', section: 'Biography' },
      averageRating: 4.5,
      numReviews: 9,
    },
    {
      title: 'The Autobiography of Malcolm X',
      author: 'Malcolm X & Alex Haley',
      isbn: '978-0-345-35068-8',
      description: 'This riveting autobiography tells the extraordinary life story of Malcolm X, from his childhood to his assassination, capturing his incredible journey and transformation.',
      publisher: 'Ballantine Books',
      publishedDate: new Date('1965-01-01'),
      pageCount: 528,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1557030609i/92057.jpg',
      category: catMap['Biography'],
      genres: ['Civil Rights', 'Memoir'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 3,
      location: { shelf: 'F1', row: '4', section: 'Biography' },
      averageRating: 4.5,
      numReviews: 8,
    },

    // ═══════════════════════════════════════
    //  SELF-HELP
    // ═══════════════════════════════════════
    {
      title: 'Atomic Habits',
      author: 'James Clear',
      isbn: '978-0-7352-1129-2',
      description: 'An easy and proven way to build good habits and break bad ones. James Clear reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
      publisher: 'Avery',
      publishedDate: new Date('2018-10-16'),
      pageCount: 320,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1535137814i/40121378.jpg',
      category: catMap['Self-Help'],
      genres: ['Productivity', 'Psychology'],
      language: 'English',
      totalCopies: 7,
      availableCopies: 4,
      location: { shelf: 'G1', row: '1', section: 'Self-Help' },
      averageRating: 4.8,
      numReviews: 25,
    },
    {
      title: 'The 7 Habits of Highly Effective People',
      author: 'Stephen R. Covey',
      isbn: '978-1-982-13727-4',
      description: 'One of the most inspiring and impactful books ever written. Covey presents a holistic, integrated, principle-centered approach for solving personal and professional problems.',
      publisher: 'Simon & Schuster',
      publishedDate: new Date('1989-08-15'),
      pageCount: 381,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1421833566i/36072.jpg',
      category: catMap['Self-Help'],
      genres: ['Leadership', 'Personal Development'],
      language: 'English',
      totalCopies: 5,
      availableCopies: 3,
      location: { shelf: 'G1', row: '2', section: 'Self-Help' },
      averageRating: 4.5,
      numReviews: 17,
    },
    {
      title: 'Think and Grow Rich',
      author: 'Napoleon Hill',
      isbn: '978-1-585-42433-7',
      description: 'This book has been called the "Granddaddy of All Motivational Literature." Napoleon Hill studied the lives of over 500 successful people and distilled their wisdom into 13 principles of success.',
      publisher: 'TarcherPerigee',
      publishedDate: new Date('1937-01-01'),
      pageCount: 320,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1465948861i/30186948.jpg',
      category: catMap['Self-Help'],
      genres: ['Finance', 'Personal Development'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 4,
      location: { shelf: 'G1', row: '3', section: 'Self-Help' },
      averageRating: 4.3,
      numReviews: 12,
    },
    {
      title: 'Deep Work',
      author: 'Cal Newport',
      isbn: '978-1-4555-8669-1',
      description: 'Rules for focused success in a distracted world. Deep work is the ability to focus without distraction on a cognitively demanding task. It\'s a skill that allows you to quickly master complicated information.',
      publisher: 'Grand Central Publishing',
      publishedDate: new Date('2016-01-05'),
      pageCount: 304,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1447899631i/25744924.jpg',
      category: catMap['Self-Help'],
      genres: ['Productivity', 'Career'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 2,
      location: { shelf: 'G1', row: '4', section: 'Self-Help' },
      averageRating: 4.5,
      numReviews: 14,
    },
    {
      title: 'The Power of Now',
      author: 'Eckhart Tolle',
      isbn: '978-1-57731-480-6',
      description: 'A guide to spiritual enlightenment. Tolle takes readers on an inspiring spiritual journey to find their true and deepest self and reach the ultimate in personal growth and spirituality.',
      publisher: 'New World Library',
      publishedDate: new Date('1997-01-01'),
      pageCount: 236,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1686928544i/6708.jpg',
      category: catMap['Self-Help'],
      genres: ['Spirituality', 'Mindfulness'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 3,
      location: { shelf: 'G1', row: '5', section: 'Self-Help' },
      averageRating: 4.3,
      numReviews: 11,
    },

    // ═══════════════════════════════════════
    //  FANTASY
    // ═══════════════════════════════════════
    {
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      isbn: '978-0-547-92822-7',
      description: 'Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life. But his contentment is disturbed when the wizard Gandalf and a company of thirteen dwarves arrive on his doorstep to whisk him away on an unexpected journey.',
      publisher: 'Mariner Books',
      publishedDate: new Date('1937-09-21'),
      pageCount: 310,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546071216i/5907.jpg',
      category: catMap['Fantasy'],
      genres: ['High Fantasy', 'Adventure'],
      language: 'English',
      totalCopies: 5,
      availableCopies: 2,
      location: { shelf: 'H1', row: '1', section: 'Fantasy' },
      averageRating: 4.7,
      numReviews: 21,
    },
    {
      title: 'Harry Potter and the Sorcerer\'s Stone',
      author: 'J.K. Rowling',
      isbn: '978-0-590-35342-7',
      description: 'Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Then, on Harry\'s eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news.',
      publisher: 'Scholastic',
      publishedDate: new Date('1997-06-26'),
      pageCount: 309,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1598823297i/42844155.jpg',
      category: catMap['Fantasy'],
      genres: ['Young Adult', 'Magic'],
      language: 'English',
      totalCopies: 6,
      availableCopies: 3,
      location: { shelf: 'H1', row: '2', section: 'Fantasy' },
      averageRating: 4.8,
      numReviews: 28,
    },
    {
      title: 'A Game of Thrones',
      author: 'George R.R. Martin',
      isbn: '978-0-553-57340-4',
      description: 'In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister forces are massing beyond the kingdom\'s protective Wall.',
      publisher: 'Bantam Books',
      publishedDate: new Date('1996-08-01'),
      pageCount: 694,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1597658524i/13496.jpg',
      category: catMap['Fantasy'],
      genres: ['Epic Fantasy', 'Political Fantasy'],
      language: 'English',
      totalCopies: 5,
      availableCopies: 4,
      location: { shelf: 'H1', row: '3', section: 'Fantasy' },
      averageRating: 4.6,
      numReviews: 19,
    },
    {
      title: 'The Name of the Wind',
      author: 'Patrick Rothfuss',
      isbn: '978-0-7564-0474-1',
      description: 'Told in Kvothe\'s own voice, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen. A high-action story written with a lyrical grace.',
      publisher: 'DAW Books',
      publishedDate: new Date('2007-03-27'),
      pageCount: 662,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1270352123i/186074.jpg',
      category: catMap['Fantasy'],
      genres: ['High Fantasy', 'Coming of Age'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 2,
      location: { shelf: 'H1', row: '4', section: 'Fantasy' },
      averageRating: 4.7,
      numReviews: 15,
    },

    // ═══════════════════════════════════════
    //  MYSTERY
    // ═══════════════════════════════════════
    {
      title: 'The Girl with the Dragon Tattoo',
      author: 'Stieg Larsson',
      isbn: '978-0-307-47347-9',
      description: 'A masterfully plotted thriller. Mikael Blomkvist, a journalist, and Lisbeth Salander, a young computer hacker, find themselves drawn into a web of corruption, murder, and dark family secrets.',
      publisher: 'Vintage Crime',
      publishedDate: new Date('2005-08-01'),
      pageCount: 672,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327868566i/2429135.jpg',
      category: catMap['Mystery'],
      genres: ['Thriller', 'Crime'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 3,
      location: { shelf: 'I1', row: '1', section: 'Mystery' },
      averageRating: 4.4,
      numReviews: 13,
    },
    {
      title: 'Gone Girl',
      author: 'Gillian Flynn',
      isbn: '978-0-307-58837-1',
      description: 'On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne\'s fifth wedding anniversary. Presents are being wrapped and dinner is planned. But Amy has disappeared.',
      publisher: 'Crown',
      publishedDate: new Date('2012-06-05'),
      pageCount: 432,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554036010i/19288043.jpg',
      category: catMap['Mystery'],
      genres: ['Thriller', 'Psychological'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 2,
      location: { shelf: 'I1', row: '2', section: 'Mystery' },
      averageRating: 4.3,
      numReviews: 16,
    },
    {
      title: 'The Hound of the Baskervilles',
      author: 'Arthur Conan Doyle',
      isbn: '978-0-14-043786-2',
      description: 'The most famous Sherlock Holmes story. When Sir Charles Baskerville is found dead on the moors with the footprints of a giant hound nearby, Holmes and Watson must unravel the mystery.',
      publisher: 'Penguin Classics',
      publishedDate: new Date('1902-04-01'),
      pageCount: 174,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327817816i/14715.jpg',
      category: catMap['Mystery'],
      genres: ['Detective', 'Classic'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 3,
      location: { shelf: 'I1', row: '3', section: 'Mystery' },
      averageRating: 4.3,
      numReviews: 8,
    },
    {
      title: 'And Then There Were None',
      author: 'Agatha Christie',
      isbn: '978-0-06-207348-8',
      description: 'Ten people are lured to a mansion on a private island off the coast of Devon. Stranded by a storm and haunted by an ancient nursery rhyme, they begin to die one by one. The bestselling mystery novel of all time.',
      publisher: 'William Morrow',
      publishedDate: new Date('1939-11-06'),
      pageCount: 272,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1638429837i/16299.jpg',
      category: catMap['Mystery'],
      genres: ['Whodunit', 'Classic'],
      language: 'English',
      totalCopies: 5,
      availableCopies: 4,
      location: { shelf: 'I1', row: '4', section: 'Mystery' },
      averageRating: 4.7,
      numReviews: 18,
    },

    // ═══════════════════════════════════════
    //  POETRY
    // ═══════════════════════════════════════
    {
      title: 'Milk and Honey',
      author: 'Rupi Kaur',
      isbn: '978-1-4494-7425-6',
      description: 'A collection of poetry and prose about survival. About the experience of violence, abuse, love, loss, and femininity. Divided into four chapters, each serves a different purpose.',
      publisher: 'Andrews McMeel',
      publishedDate: new Date('2014-11-04'),
      pageCount: 204,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1488022696i/23519490.jpg',
      category: catMap['Poetry'],
      genres: ['Contemporary Poetry', 'Feminism'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 3,
      location: { shelf: 'J1', row: '1', section: 'Poetry' },
      averageRating: 4.3,
      numReviews: 14,
    },
    {
      title: 'The Sun and Her Flowers',
      author: 'Rupi Kaur',
      isbn: '978-1-4494-8679-2',
      description: 'From Rupi Kaur, the bestselling author of Milk and Honey, comes a long-awaited second collection of poetry. A vibrant and transcendent journey about growth and healing.',
      publisher: 'Andrews McMeel',
      publishedDate: new Date('2017-10-03'),
      pageCount: 256,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1496598276i/35297186.jpg',
      category: catMap['Poetry'],
      genres: ['Contemporary Poetry', 'Love'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 3,
      location: { shelf: 'J1', row: '2', section: 'Poetry' },
      averageRating: 4.2,
      numReviews: 9,
    },
    {
      title: 'Leaves of Grass',
      author: 'Walt Whitman',
      isbn: '978-0-14-042451-4',
      description: 'The life work of American poet Walt Whitman. First published in 1855, Whitman revised and expanded it throughout his life. It is a landmark in the history of American literature.',
      publisher: 'Penguin Classics',
      publishedDate: new Date('1855-07-04'),
      pageCount: 464,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1559259309i/5765.jpg',
      category: catMap['Poetry'],
      genres: ['Classic Poetry', 'American Literature'],
      language: 'English',
      totalCopies: 2,
      availableCopies: 2,
      location: { shelf: 'J1', row: '3', section: 'Poetry' },
      averageRating: 4.3,
      numReviews: 6,
    },
    {
      title: 'The Collected Poems of Rumi',
      author: 'Rumi',
      isbn: '978-0-679-42536-2',
      description: 'The essential collection of Rumi\'s mystical and spiritual poetry. Rumi is the most popular poet in the United States, and his poems speak of love, joy, and the search for the divine.',
      publisher: 'Everyman\'s Library',
      publishedDate: new Date('1273-01-01'),
      pageCount: 432,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320553018i/2868153.jpg',
      category: catMap['Poetry'],
      genres: ['Sufi Poetry', 'Spirituality'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 2,
      location: { shelf: 'J1', row: '4', section: 'Poetry' },
      averageRating: 4.6,
      numReviews: 10,
    },
    {
      title: 'The Essential Rumi',
      author: 'Jalal ad-Din Rumi (Trans. Coleman Barks)',
      isbn: '978-0-06-250959-4',
      description: 'This revised and expanded edition of The Essential Rumi includes many new poems that have never before appeared in English. Coleman Barks\' translations capture the ecstatic energy of Rumi\'s voice.',
      publisher: 'HarperOne',
      publishedDate: new Date('1995-05-01'),
      pageCount: 412,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1246265728i/95574.jpg',
      category: catMap['Poetry'],
      genres: ['Sufi Poetry', 'Spirituality', 'Translation'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 3,
      location: { shelf: 'J1', row: '5', section: 'Poetry' },
      averageRating: 4.5,
      numReviews: 8,
    },

    // ═══════════════════════════════════════
    //  EXTRA — MIXED CATEGORIES
    // ═══════════════════════════════════════
    {
      title: 'The Catcher in the Rye',
      author: 'J.D. Salinger',
      isbn: '978-0-316-76948-0',
      description: 'The story of Holden Caulfield, a teenage boy who has been expelled from prep school and is wandering through New York City. A classic coming-of-age tale that has become iconic.',
      publisher: 'Little, Brown',
      publishedDate: new Date('1951-07-16'),
      pageCount: 277,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1398034300i/5107.jpg',
      category: catMap['Fiction'],
      genres: ['Coming of Age', 'Classic'],
      language: 'English',
      totalCopies: 3,
      availableCopies: 3,
      location: { shelf: 'A1', row: '6', section: 'Fiction' },
      averageRating: 4.2,
      numReviews: 11,
    },
    {
      title: 'Brave New World',
      author: 'Aldous Huxley',
      isbn: '978-0-06-085052-4',
      description: 'Aldous Huxley\'s profoundly important classic of world literature. A masterful satire of a future utopia that has become a benchmark for generations to come.',
      publisher: 'Harper Perennial',
      publishedDate: new Date('1932-01-01'),
      pageCount: 288,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1575014612i/5129.jpg',
      category: catMap['Fiction'],
      genres: ['Dystopian', 'Science Fiction'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 4,
      location: { shelf: 'A1', row: '7', section: 'Fiction' },
      averageRating: 4.4,
      numReviews: 12,
    },
    {
      title: 'Thinking, Fast and Slow',
      author: 'Daniel Kahneman',
      isbn: '978-0-374-53355-7',
      description: 'Nobel laureate Daniel Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think — System 1 fast and intuitive, System 2 slow and deliberate.',
      publisher: 'Farrar, Straus and Giroux',
      publishedDate: new Date('2011-10-25'),
      pageCount: 499,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1317793965i/11468377.jpg',
      category: catMap['Science'],
      genres: ['Psychology', 'Behavioral Economics'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 2,
      location: { shelf: 'B1', row: '6', section: 'Science' },
      averageRating: 4.5,
      numReviews: 15,
    },
    {
      title: 'The Subtle Art of Not Giving a F*ck',
      author: 'Mark Manson',
      isbn: '978-0-06-245771-4',
      description: 'A counterintuitive approach to living a good life. Mark Manson argues that improving our lives hinges not on our ability to turn lemons into lemonade, but on learning to stomach lemons better.',
      publisher: 'HarperOne',
      publishedDate: new Date('2016-09-13'),
      pageCount: 224,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1465767644i/28257707.jpg',
      category: catMap['Self-Help'],
      genres: ['Personal Development', 'Humor'],
      language: 'English',
      totalCopies: 5,
      availableCopies: 3,
      location: { shelf: 'G1', row: '6', section: 'Self-Help' },
      averageRating: 4.2,
      numReviews: 19,
    },
    {
      title: 'Dune',
      author: 'Frank Herbert',
      isbn: '978-0-441-17271-9',
      description: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world. It is a stunning blend of adventure and mysticism, environmentalism and politics.',
      publisher: 'Ace Books',
      publishedDate: new Date('1965-08-01'),
      pageCount: 688,
      coverImage: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1555447414i/44767458.jpg',
      category: catMap['Fantasy'],
      genres: ['Science Fiction', 'Space Opera'],
      language: 'English',
      totalCopies: 4,
      availableCopies: 2,
      location: { shelf: 'H1', row: '5', section: 'Fantasy' },
      averageRating: 4.6,
      numReviews: 17,
    },
  ];

  await Book.insertMany(books);
  console.log(`${books.length} books seeded successfully`);
};

module.exports = seedBooks;
